name: CI

on:
  push:
    branches:
      - master
      - dev

    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            !~/.npm/_logs
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      
      - name: Install dependecies
        run: deno install

      - name: Run Linter
        run: deno lint app/ components/ lib/

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: "actions/checkout@v4"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            !~/.npm/_logs
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      
      - name: Install dependecies
        run: deno install

      - name: Run tests
        run: deno test
          
